### ISSUE TITLE
Images are given height and width attributes which don't scale responsively

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#11]
![powerkit](https://user-images.githubusercontent.com/2205158/49613884-b43aa700-f976-11e8-9479-4d6954a90ad6.gif)

How can we use Wagtail's image function to make our images responsive?

**Comment by boyombo** [comment]
I removed the width and height from the images in the blog page, they seem to be a bit more responsive. I tried to do same on the generation page but the image was too large.
Is there a css rule to apply to the images?

**Comment by theadamparker** [comment]
@boyombo I added `height: auto` to our images and things seem to be in better shape. Are you still seeing issues anywhere?

**Comment by boyombo** [comment]
Nope, looks ok
