### ISSUE TITLE
Develop head content—Title tags, meta tags

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#15]
The site should have default title tag structure, and meta description. Possibly with the ability to customize for individual pages.

**Comment by boyombo** [comment]
There is a block tag on the base.html template that can be overridden on individual templates to provide the title information for them.

**Comment by theadamparker** [comment]
We'll also want to build out meta tags for sharing on social media. [Examples here.](https://css-tricks.com/essential-meta-tags-social-media/)

**Comment by theadamparker** [comment]
@boyombo Is there a way to define a default meta description and keywords in Wagtail's site settings?

**Comment by boyombo** [comment]
I have added meta data to the snippets, and placed them in the base template.
