### ISSUE TITLE
Add Training Module skeleton structure

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#21]
Top nav title should be `Training`. We're not ready to populate this with content, but we know the general structure, as discussed on the December 12th call.

**Comment by theadamparker** [comment]
@boyombo For this week, it would be best to include this page in the Top nav, and add a class like `.topNav__item--locked`. I can develop the CSS for that class to make it look unavailable (maybe greyed-out and italicized).

It should be clear that the Training Module is part of the site, but not launched in this beta version.

**Comment by boyombo** [comment]
I have added the (very) basic structure.
Next steps will be 

- [ setup login/signup so users will be associated with training sessions ]
- [ Then tracking training modules completed as well as stage reached for users ]
- [ Then make the pages look a little more decent so the module is useable ]

**Comment by theadamparker** [comment]
I think we're pretty far into developing this structure, and certainly have the bones of it built out.
