### ISSUE TITLE
Issues CMS template sections don't create multiple paragraphs

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#23]
Fields like Key Players, and Policy Background collapse all content to a single paragraph tag.

![screen shot 2018-12-13 at 11 22 36 am](https://user-images.githubusercontent.com/2205158/49952172-6f0ffb00-fec9-11e8-8221-14dd16280d21.png)

We'll need to resolve this by using some other type of field. I'd love for this to be written in Markdown in the CMS if possible 😎

**Comment by boyombo** [comment]
There are 2 approaches to this issue:

1. We remove the enclosing `<p>` tag in the page and use the RichTextField in the cms instead (the line-break translates to `<p>`.

2. We make a MarkDown field for editing...

I think (1) is easiest to implement so we go with this first, and do the MarkDown field if it doesn't work out

**Comment by boyombo** [comment]
I used the RichText field, please re-open if you need the markdown instead
