### ISSUE TITLE
Develop Blog post author functionality

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#30]

**Comment by theadamparker** [comment]
Multiple Authors will be contributing to the blog. We'll need to establish a way to input an author's name, and possibly more info. This could be a simple input field for Name, or it could be something more complex like an account, with an index page for each contributor. This may depend on Wagtail's abilities.

**Comment by boyombo** [comment]
I added an author field, though it is tied to a user.

**Comment by boyombo** [comment]
changed the field to plain text
