### ISSUE TITLE
Lessons aren't activated until a user clicks "start training"

### ISSUE THREAD

**Issue by theadamparker** [theReboot/powertoolkit#32]
![docs](https://user-images.githubusercontent.com/2205158/50989888-94028880-14de-11e9-8e86-5f22088aeb09.gif)

After creating a new user account, if you begin by clicking the first lesson rather than clicking the yellow *Start Training* button, a lesson can't be completed (see error in GIF).

This *End* button behaves properly after the *Start Training* button has been clicked on the Learning index page.

**Comment by theadamparker** [comment]
Related issue, the list of lessons doesn't incorporate the proper ongoing/completed/pending state until after *Start Training* has been clicked. Screenshots for reference:

![screen shot 2019-01-10 at 1 55 04 pm](https://user-images.githubusercontent.com/2205158/50990263-944f5380-14df-11e9-919d-22dc5b0b3d71.png)
Before clicking *Start Training*

![screen shot 2019-01-10 at 1 55 17 pm](https://user-images.githubusercontent.com/2205158/50990286-a29d6f80-14df-11e9-9d47-79e8dcc962c2.png)
After clicking *Start Training*.

**Comment by boyombo** [comment]
True, it should be pending before the training starts

**Comment by boyombo** [comment]
So what I have done is to wait till you click "Start Training" before enabling the lessons.

**Comment by theadamparker** [comment]
@boyombo This is better. Is it possible to unlock the first lesson before clicking the "start training" button? For example, a user that has just signed-up will see the first lesson as pending, when it's actually available. 

![screen shot 2019-01-14 at 10 56 11 am](https://user-images.githubusercontent.com/2205158/51123970-2bbbeb80-17eb-11e9-8df7-23ecda909c73.png)

**Comment by boyombo** [comment]
Ok, no problem

**Comment by theadamparker** [comment]
@boyombo Getting there! One more bug. If you're not logged in you can still click first lesson.

![chart](https://user-images.githubusercontent.com/2205158/51185220-87967b00-18a4-11e9-9507-21c31576fe11.gif)
